# Generated by Django 3.2 on 2022-06-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('item', 'email')},
        ),
    ]
